name: SomChat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  firebase_storage: ^11.0.6
  image_picker: ^0.8.6
  flutter_launcher_icons: ^0.11.0
  lottie: ^2.0.0
  country_phone_code_picker: ^0.0.41
  pinput: ^2.2.12
  get_time_ago: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.ico"
flutter:

  uses-material-design: true

  assets:
    - logo.png
    - verify.png
    - assets/images/animate.json
    - send.png

